-- 工作台常用筛选、项目权限与审计追溯索引。
CREATE INDEX "Projects_status_lifecycle_stage_idx" ON "Projects"("status", "lifecycle_stage");
CREATE INDEX "Projects_owner_id_idx" ON "Projects"("owner_id");
CREATE INDEX "Phases_project_id_sort_order_idx" ON "Phases"("project_id", "sort_order");
CREATE INDEX "Tasks_project_id_status_idx" ON "Tasks"("project_id", "status");
CREATE INDEX "Tasks_project_id_assignee_id_idx" ON "Tasks"("project_id", "assignee_id");
CREATE INDEX "Tasks_project_id_phase_id_idx" ON "Tasks"("project_id", "phase_id");
CREATE INDEX "Tasks_due_date_idx" ON "Tasks"("due_date");
CREATE INDEX "BOM_Items_project_id_status_idx" ON "BOM_Items"("project_id", "status");
CREATE INDEX "BOM_Items_project_id_phase_id_idx" ON "BOM_Items"("project_id", "phase_id");
CREATE INDEX "BOM_Items_project_id_eta_idx" ON "BOM_Items"("project_id", "eta");
CREATE INDEX "Tech_Specs_project_id_phase_id_idx" ON "Tech_Specs"("project_id", "phase_id");
CREATE INDEX "Change_Logs_project_id_status_created_at_idx" ON "Change_Logs"("project_id", "status", "created_at");
CREATE INDEX "Users_role_id_status_idx" ON "Users"("role_id", "status");
CREATE INDEX "Project_Members_user_id_idx" ON "Project_Members"("user_id");
CREATE INDEX "Change_Requests_project_id_status_created_at_idx" ON "Change_Requests"("project_id", "status", "created_at");
CREATE INDEX "Change_Impacts_eco_id_entity_type_idx" ON "Change_Impacts"("eco_id", "entity_type");
CREATE INDEX "Approval_Records_target_type_target_id_created_at_idx" ON "Approval_Records"("target_type", "target_id", "created_at");
CREATE INDEX "Task_Dependencies_successor_id_idx" ON "Task_Dependencies"("successor_id");
CREATE INDEX "Milestones_project_id_date_idx" ON "Milestones"("project_id", "date");
CREATE INDEX "Time_Entries_task_id_date_idx" ON "Time_Entries"("task_id", "date");
CREATE INDEX "Time_Entries_user_id_date_idx" ON "Time_Entries"("user_id", "date");
CREATE INDEX "Documents_project_id_updated_at_idx" ON "Documents"("project_id", "updated_at");
CREATE INDEX "Documents_category_idx" ON "Documents"("category");
CREATE INDEX "Doc_Versions_document_id_created_at_idx" ON "Doc_Versions"("document_id", "created_at");
CREATE UNIQUE INDEX "Entity_Links_task_id_entity_type_entity_id_key" ON "Entity_Links"("task_id", "entity_type", "entity_id");
CREATE INDEX "Entity_Links_entity_type_entity_id_idx" ON "Entity_Links"("entity_type", "entity_id");
CREATE INDEX "Comments_entity_type_entity_id_created_at_idx" ON "Comments"("entity_type", "entity_id", "created_at");
CREATE INDEX "Audit_Logs_entity_type_entity_id_created_at_idx" ON "Audit_Logs"("entity_type", "entity_id", "created_at");
CREATE INDEX "Audit_Logs_user_id_created_at_idx" ON "Audit_Logs"("user_id", "created_at");
